
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    ports:
      - "27017:27017"
    volumes:
      - ./workspace:/workspace
      - type: volume
        source: mongodb_data_volume
        target: /data/db
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s


  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "27020:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 2s
      timeout: 5s
      retries: 5

  

volumes:
  mongodb_data_volume:
    driver: local
